version: '3.8'

services:
  bot:
    image: sasquatchme/crm_service:crm_bot
    container_name: tg_bot
    volumes:
      - ./database.db:/database.db
  web:
    image: sasquatchme/crm_service:crm_web
    container_name: flask_app
    volumes:
      - ./database.db:/database.db  # Монтируем папку для хранения базы данных
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development

    # Монтируем ту же папку для доступа к базе данных
