version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    container_name: tg_bot
    volumes:
      - ./database.db:/database.db
      - static_data:/app/web_app/static/images
  web:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask_app
    volumes:
      - ./database.db:/database.db
      - static_data:/app/web_app/static/images
      - .:/app
    ports:
      - "5000:5000"


volumes:
  static_data:

