name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push bot image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-bot
          push: true
          tags: sasquatchme/crm_service:crm_bot

      - name: Build and push web image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-flask
          push: true
          tags: sasquatchme/crm_service:crm_web

      - name: Deploy to server
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} root@147.45.103.30 "docker pull sasquatchme/crm_service:crm_bot && docker pull sasquatchme/crm_service:crm_web && docker-compose -f /crm_app/docker_compose.yml up"
