name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set image tag
      run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

    - name: Build and push bot image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.bot
        push: true
        tags: sasquatchme/crm_service:crm_bot:${{ env.IMAGE_TAG }}

    - name: Build and push web image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile.web
        push: true
        tags: sasquatchme/crm_service:crm_web:${{ env.IMAGE_TAG }}

    - name: Deploy to server
      run: |
        ssh root@147.45.103.30 "docker-compose -f /crm_app/docker-compose.yml pull && docker-compose -f /crm_app/docker-compose.yml up -d"

